- README.md
- scripts/Atoms_finding_sire_test.ipynb
- scripts/addanchors.py
- scripts/addanchors_exampleinputs.txt
Created the "scripts" folder. 
Currently contains the "addanchors.py" script which creates a modified system with dummy atoms designed to be used in cartesian restraints. It also creates a "restraint.cfg" file which can be pasted directly in to a SOMD (latest version) config file in order to create the restrained atom pairs.
Also included is a jupyter notebook that shows an example of selecting heavy atoms within a given range of a ligand using sire.
> Feature addanchors

- src/somd2/runner/_runner.py
- src/somd2/runner/_sire_merge_runsim.py
This PR converts the energy trajectory DataFrame to alchemlyb format using the new in-built Sire functionality. This simplifies the analysis in BioSImSpace since the DataFrame is (mostly) already in the required format. Since DataFrame attributes are lost of conversion to Parquet format, I've included them as an additional metadata key.
> Convert DataFrame to alchemlyb format to simplify analysis

- src/somd2/config/_config.py
- src/somd2/runner/_dynamics.py
- src/somd2/runner/_runner.py
- tests/conftest.py
- tests/runner/test_config.py
- tests/runner/test_hmr.py
- tests/runner/test_restart.py
This PR closes #6 by allowing `somd2` to be able to simulate systems where HMR has already been applied. This is done by detecting the existing `h_mass_factor` and applying a new factor of `Config.h_mass_factor /  h_mass_factor`. No repartitioning is performed if the existing factor matches the one specified by the config.
I've added a test to make sure that the HMR factor is detected correctly and that the value is correctly updated following rescaling. I've also parameterised the restart test over two perturbable systems, one with HMR and one without, allowing us to confirm that the runner does work if HMR is already present.
Due to the limited precision of atomic masses in text based input files I've added some rounding when comparing hydrogen masses to ensure that we don't …
> Fix issue #6

- src/somd2/runner/_dynamics.py
Quick fix for a possible source of instability, changes "none" to None in both "perturbable-constraint" and "constraint"
> Fix for perturbable constraints, also changes constraints for consistency

- src/somd2/config/_config.py
- src/somd2/runner/_dynamics.py
This PR exposes the `cutoff` kwarg used in `sire` minimisation and dynamics. (Previously we only exposed the `cutoff_type` and let `sire` choose the default `cutoff`.) This option is exposed as a string, which is (generally) parsed as a length based general unit. I've added support for the special case of `cutoff="infinite"`, which can't be parsed in the same way. At present we don't automatically adjust the `cutoff` for vacuum simulations. If this is something that we want to do, then it can be combined with the space check that enforces `cutoff_type="rf` for vacuum simulations, e.g. we could set `cutoff="infinite"` here if needed.
> Expose cutoff kwarg

- src/somd2/__init__.py
- src/somd2/app/__init__.py
- src/somd2/app/run.py
- src/somd2/config/__init__.py
- src/somd2/config/_config.py
- src/somd2/io/__init__.py
- src/somd2/io/_io.py
- src/somd2/runner/__init__.py
- src/somd2/runner/_dynamics.py
- src/somd2/runner/_runner.py
- src/somd2/runner/_somd1.py
- tests/conftest.py
- tests/runner/test_config.py
This PR adds support for a `somd1` "compatibility" mode. This ensures that bonded terms in the merge molecule are modified so that the perturbation is consistent with the default that is used for `somd1`, where modifications are made via the "pert" file. For consistency, the water topology is also switched to AMBER format when using compatibility mode. This ensures that _exact_ same solvent parameters are used. The detection of the water topology is crude, but should cover all default cases we require for `somd1` comparisons. (This isn't meant to be a long-lived feature.)
The PR also exposes some addition Sire dynamics keyword arguments that have been added, e.g. the `com_reset_frequency` and `dynamic_constraints`. It also fixes a few minor bugs where keyword arguments weren't properly …
> Add SOMD1 compatibility mode

- src/somd2/runner/_somd1.py
This PR fixes the somd1 compatibility mode by exhaustively searching bonded potentials to find shared terms. Previously I had forgotten that the containers don't preserve order, so matching directly between end states wasn't robust. This has been tested against problematic vacuum perturbations from the hydration free energy test suite and results are now in perfect agreement with somd1.
[closes #22]
> Fix issue #22

- src/somd2/app/run.py
- src/somd2/config/_config.py
- src/somd2/runner/_runner.py
- src/somd2/runner/_somd1.py
This PR moves the `--pert-file` CLI option into the `Config` class so that it is stored to the YAML configuration file. The perturbable system is now created during the runner setup and `somd1_compatibility` is automatically set to `True` when running using a reference state and perturbation file. (As a safety net.)
> Move pert_file CLI option into Config class

- src/somd2/runner/_runner.py
SOMD2 was exiting without raising an error when run in serial (the error was raised in `_setup_dynamics`). I've also added a missing f-string.
> Ensure that Exceptions are Logged When Running in Serial

- src/somd2/config/_config.py
This PR fixes #37  by adding a logger warning when the h_mass_factor is set to < 1.0 in the configuration.
> [PR] fix_37

- src/somd2/__init__.py
- src/somd2/app/run.py
- src/somd2/runner/_runner.py
This PR builds on and closes #39. The `somd2` and `sire` versions are now stored on startup and reported if running in a non-interactive fashion. The versions are also added as additional metadata to the parquet energy trajectory files, so we can more easily cross reference data with versions, i.e. we don't need to keep or grep the log files. I decided not to store the versions in the stream file since we already have validation for configuration compatibility when restarting. (I'm happy to add it if you think it would be beneficial.)
@fjclark: Does this work for you? I wanted to take the logging outside of the `Config` class so that it isn't triggered when unpicking an object of this type, or if the user is creating multiple configs in a script. Basically I want the info to be visible …
> Improve versioning

- src/somd2/config/_config.py
- src/somd2/runner/_dynamics.py
- src/somd2/runner/_runner.py
- tests/runner/test_lambda_values.py
- tests/runner/test_restart.py
This PR closes #41 by adding support for configuring the runner to use a custom list of lambda values. This can be passed from the command-line as follows:
```
somd2 system.bss --lambda-values 0 0.5 1
```
The options are parsed as multiple strings and conversion to float is attempted and validated when the `Config` is created. We also check that the values are valid, i.e. between 0 and 1 inclusive. This option takes precedence over `num_lambda`, i.e. `num_lambda` will be set to the value of `len(lambda_values)`.
I've also fixed a few docstring issues that I found.
> Add support for using a custom list of lambda values

- src/somd2/runner/_runner.py
- src/somd2/runner/_somd1.py
This PR fixes the form of null bonded terms used during the `somd1` compatibility mode. By not adding the terms in the end state in which they should be nulled, `sire` will correctly add a null term that zeros the force constant but preserves the other components, e.g. `r0`, `theta0`, `phase`, `periodicity`, from the opposite state. When adding an explicit null term, conversion to a CAS expression creates a _fully_ nulled potential, so all components are zero, i..e. a bond would have its force constant _and_ bond size perturbed to zero. I don't think this causes issues in practice, since it's just a different pathway through lambda space, but it is good to be consistent with what is done for `somd1`.
> Fix form of null bonded terms

- README.md
- src/somd2/config/_config.py
- src/somd2/runner/_dynamics.py
- src/somd2/runner/_runner.py
- src/somd2/runner/_somd1.py
This PR adds support for writing the energy components (from each force) to a log file for debugging purposes with the `--save-energy-components` command-line option. This also builds on [OpenBioSim/sire#198](https://github.com/OpenBioSim/sire/pull/198) and [OpenBioSim/biosimspace#295](https://github.com/OpenBioSim/biosimspace/pull/295) to prevent perturbation of the LJ sigma parameter for ghost atoms, which causes instability during perturbation.
> Add support for writing energy components to file and preserving the LJ sigma parameter for ghost atoms

- README.md
> Adds CUDA documentation to README

- src/somd2/__init__.py
- src/somd2/runner/_runner.py
This PR moves the logging of `somd2` and `sire` versions to the `Runner` constructor to ensure that they are logged to file (when a log file is specified). Previously this was done on startup, which occurs before the log file sink is created.
Test failures are due to missing `sire` and `BioSimSpace` builds for the respective platforms. Should hopefully be fixed soon.
> Make sure versions are logged to file

- src/somd2/runner/_runner.py
This PR adds a small fix to ensure that the asymmetric constraint warning is only printed once, i.e. it isn't duplicated if multiple constraints don't match between end states. I've also added an initial check to make sure that the number of constraints is the same, then check each constraint one-by-one.
> Only print constraint warning once

- .github/workflows/main.yaml
- src/somd2/config/_config.py
- src/somd2/runner/_dynamics.py
- src/somd2/runner/_runner.py
- tests/runner/test_alchemical_ions.py
- tests/runner/test_restart.py
This PR adds support for adding alchemical ions to enforce charge neutrality during a perturbation. Currently the number of ions to apply to the perturbed state is configured via the `--charge-difference` command-line option. This specifies the difference in charge between the perturbed and reference states, i.e. charge(perturbed) minus charge(reference). For reference, the indices of the water molecules that are perturbed are written to the log. We also check the difference in end-state charge for _all_ simulations and warn the user when there is a mismatch, i.e. suggesting to use `--charge-difference` if they want to preserve neutrality. In future, all of this could be automated if we want to completely remove the option, e.g. we could have some `--charge-neutral` flag that is `True` by …
> Add alchemical ion support

- src/somd2/config/_config.py
- src/somd2/runner/_runner.py
1) Automatically keep the charge constant unless the user has specified a value, warning if value doesn't match.
2) If present, use existing ion parameters when creating the alchemical ion.
(I'm just finding a system to test this on locally.)
> Alchemical ion improvements

- src/somd2/runner/_runner.py
- tests/conftest.py
- tests/runner/test_alchemical_ions.py
This PR improves the logic for detecting existing free ions in a system so that we match force field parameters when creating alchemical ions. We now search for all ions and take any that are monatomic molecules. If none are found, then we also search for the opposite ion (swapped charge) and invert the alchemical ion perturbation if one is found. For example, if we need to add an Na+ to the perturbed state but don't find one, we could instead use the parameters for a Cl- (if present) and just invert the merged molecule and perturb from ion to water rather than water to ion.
I'll try to create a minimal test system for this and update the PR when done.
> Improve search for existing ions

- src/somd2/config/_config.py
- src/somd2/runner/_dynamics.py
This PR fixes the long-standing constraint asymmetry bug by reinitialising the context when lambda is updated following the creation of a dynamics object. I've also added support for the new `timeout` option in the Sire minimiser to avoid long hangs.
> Add timeout to minimiser and fix constraint asymmetry bug

- src/somd2/config/_config.py
- src/somd2/runner/_runner.py
Fixes issue #67 , also fixes behaviour when `checkpoint_frequency=0`
> Fix for #67

- src/somd2/config/_config.py
- src/somd2/runner/_base.py
- src/somd2/runner/_runner.py
- tests/runner/test_lambda_values.py
This PR fixes the handling of REST2 scale factors when running simulations at a sub-set of the total number of lambda windows, or sampling energies at a subset of values.
> Fix issue #69
